version: '3.8'

services:
  ipinfo:
    container_name: roticeh-ipinfo
    build:
      context: .
      dockerfile: Dockerfile
    image: roticeh-ipinfo:latest
    ports:
      - "9755:9755"
    restart: always
    
    environment:
      - IPINFO_SERVER_PORT=9755
      - IPINFO_SERVER_NAME=IPInfo
      # - SECRET_TOKEN=rtch_live_prod_secret_key_change_me_on_server
      - GEO_DB_PATH=./db/GeoLite2-City.mmdb
      - ASN_DB_PATH=./db/GeoLite2-ASN.mmdb
      - APP_ENV=production


    volumes:
      - ./db:/dist/db
      # - ./config.yaml:/dist/config.yaml

        
    deploy:
      resources:
        limits:
          cpus: '0.50'     
          memory: 256M     
        reservations:
          memory: 64M   

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  
    healthcheck:

      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9755/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  db-updater:
    image: docker:cli
    container_name: roticeh-ipinfo-updater
    restart: always
    volumes:
      - ./db:/db-data
        - /var/run/docker.sock:/var/run/docker.sock
    command: >
      /bin/sh -c "
      echo '0 3 */5 * * wget -qO /db-data/GeoLite2-City.mmdb https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb && wget -qO /db-data/GeoLite2-ASN.mmdb https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb && docker restart roticeh-ipinfo' > /etc/crontabs/root &&
      crond -f -l 2
      "

#  STYLE 2
  # db-updater:
  #   image: alpine:latest
  #   container_name: roticeh-ipinfo-updater
  #   restart: always
  #   volumes:
  #     - ./db:/db-data
  #   command: >
  #     /bin/sh -c "while true; do
  #       echo 'Downloading latest MaxMind databases...';
  #       wget -qO /db-data/GeoLite2-City.mmdb 'https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb';
  #       wget -qO /db-data/GeoLite2-ASN.mmdb 'https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb';
  #       echo 'Download complete. Sleeping for 5 days...';
  #       sleep 432000;
  #     done"